[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildContext = "backend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PORT = { default = "8000" }
DATABASE_URL = { default = "sqlite:///./triaging.db" }
